global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # If you're running AI-ML service on port 5000
  - job_name: "ai-ml-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["ai_service:5000"]
