global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node/Container metrics
  # For instance, if you use cAdvisor or node-exporter:
  # - job_name: "node"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]

rule_files:
  - "/etc/prometheus/alerts.rules"
