version: "3.8"

services:
  aggregator:
    build:
      context: ..
      dockerfile: federated-learning/docker/Dockerfile.aggregator
    container_name: fl_aggregator
    ports:
      - "8000:8000"
    volumes:
      - ../federated-learning/aggregator:/app/aggregator
      - ../federated-learning/common:/app/common
      - ../federated-learning/config:/app/config
    networks:
      - fl_net

  client:
    build:
      context: ..
      dockerfile: federated-learning/docker/Dockerfile.client
    container_name: fl_client
    ports:
      - "9000:9000"
    volumes:
      - ../federated-learning/client:/app/client
      - ../federated-learning/common:/app/common
      - ../federated-learning/config:/app/config
    networks:
      - fl_net

networks:
  fl_net:
    name: fl_network
