# ai-config.yaml

llm_model: "sentence-transformers/all-MiniLM-L6-v2"
model_path: "models/model.pkl"

vector_store_api_key: "YOUR_PINECONE_API_KEY"
vector_store_environment: "us-west1-gcp"
vector_store_index_name: "ai-ml-index"
vector_store_dimension: 384