# ai_config.yaml
model_settings:
  llm_provider: "openai"     # or "hf" (Hugging Face), "local" for local models
  vector_db: "weaviate"      # or "pinecone" / "faiss"
  symbolic_reasoning_enabled: true

privacy:
  anonymize_responses: true
  maximum_tokens: 1024
